// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dialogs} from '../models';

export function OpenFileDialog(arg1:dialogs.OpenFileDialogParam):Promise<string>;
